from __future__ import annotations

class Engine:
    def setProperty(self, name: str, value: str | float) -> None: ...
    def say(self, text: str | None, name: str | None = None) -> str | None: ...
    def runAndWait(self) -> None: ...

def init(driverName: str | None = None, debug: bool = False) -> Engine: ...
